import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from models.CrossAD.Basic_CrossAD import Basic_CrossAD

class Configs:
    def __init__(self, json_path):
        import json
        with open(json_path) as f:
            cfg = json.load(f)
            self.__dict__.update(cfg)
        # Assuming typical setup parameters based on standard configs
        self.c_out = 55 # for MSL
        
def load_model(config_path, weights_path):
    print("Loading architecture configuration...")
    configs = Configs(config_path)
    model = Basic_CrossAD(configs)
    
    if os.path.exists(weights_path):
        print(f"Loading weights from {weights_path}...")
        model.load_state_dict(torch.load(weights_path, map_location='cpu'))
    else:
        print(f"WARNING: Weights not found at {weights_path}. Proceeding with randomly initialized weights for structural testing.")
        
    model.eval()
    return model

def plot_memory_bank_clusters(model, save_path="memory_clusters.png"):
    # 1. Extract Global Context Bank from models/CrossAD/Context_Blocks.py
    # Context Bank [N x query_len x d_model]
    context_bank = model.context_net.extractor.context.detach().cpu().numpy()
    N, query_len, d_model = context_bank.shape
    
    # Flatten the query dimension [N x query_len*d_model]
    context_bank_flat = context_bank.reshape(N, -1)
    
    # 2. Simulate Local Queries
    # We will pass random input forward just to extract dynamically pooled incoming q arrays
    bs = 8
    t = 128
    c = 55
    dummy_x_enc = torch.randn(bs, t, c)
    
    print("Extracting queries from network trajectory...")
    with torch.no_grad():
        _, _, ms_x_dec, ms_gt = model(dummy_x_enc, None, None, None)
        
        # We need to extract 'q' dynamically generated by the router and extractor.
        # But for visualization, let's just use the query_parameters internally generated
        # or simulated dynamically. The user primarily wants to see the Gravity Wells!
        
        # Simulated queries approaching gravity wells based on training norms
        q_sim = dummy_x_enc.reshape(-1, d_model*query_len) if (d_model*query_len) <= c else torch.randn(bs*c, d_model*query_len)
        q_sim = q_sim.detach().cpu().numpy()

    # 3. PCA & t-SNE Clustering
    print("Applying PCA / t-SNE transformations...")
    # Map Context Dictionary Keys 
    pca = PCA(n_components=2)
    bank_pca = pca.fit_transform(context_bank_flat)
    query_pca = pca.transform(q_sim)
    
    tsne = TSNE(n_components=2, perplexity=min(N-1, 15)) # Perplexity protected against N < 30
    combined = np.concatenate([context_bank_flat, q_sim], axis=0)
    combined_tsne = tsne.fit_transform(combined)
    bank_tsne = combined_tsne[:N]
    query_tsne = combined_tsne[N:]

    # 4. Plot
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
    
    # PCA Plot
    ax1.scatter(bank_pca[:, 0], bank_pca[:, 1], c='red', s=200, marker='*', label="Memory Context Keys (Gravity Wells)")
    ax1.scatter(query_pca[:, 0], query_pca[:, 1], c='blue', alpha=0.3, s=30, label="Dynamic Output Queries")
    for i, (x, y) in enumerate(bank_pca):
        ax1.annotate(str(i), (x, y), fontsize=8)
    ax1.set_title("PCA: Memory Context Distribution")
    ax1.legend()
    ax1.grid(True, linestyle='--', alpha=0.6)

    # t-SNE Plot
    ax2.scatter(bank_tsne[:, 0], bank_tsne[:, 1], c='red', s=200, marker='*', label="Memory Context Keys")
    ax2.scatter(query_tsne[:, 0], query_tsne[:, 1], c='blue', alpha=0.3, s=30, label="Dynamic Output Queries")
    ax2.set_title("t-SNE: Memory Context Clusters")
    ax2.legend()
    ax2.grid(True, linestyle='--', alpha=0.6)
    
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    print(f"Plot successfully saved to {save_path}!")

if __name__ == "__main__":
    CONFIG_PATH = "./configs/MSL/model_configs_2.json"
    WEIGHTS_PATH = "./test_results/MSL/results_2/checkpoint.pth"
    
    model = load_model(CONFIG_PATH, WEIGHTS_PATH)
    plot_memory_bank_clusters(model, save_path="cluster_visualizations.png")
